### ISSUE TITLE
Crash reported on VE data - failed to invert structural->std space transformation

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/oxasl#4]
From Winok::

```
ERROR: 0-dimensional array given. Array must be at least two-dimensional
Traceback (most recent call last):
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/oxford_asl.py", line 160, in main
    oxasl(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/oxford_asl.py", line 180, in oxasl
    oxasl_preproc(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/oxford_asl.py", line 249, in oxasl_preproc
    calib.calculate_m0(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/calib.py", line 66, in calculate_m0
    wsp.calibration.m0 = get_m0_refregion(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/calib.py", line 440, in get_m0_refregion
    get_tissrefmask(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/calib.py", line 617, in get_tissrefmask
    reg.reg_struc2std(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/reg.py", line 234, in reg_struc2std
    wsp.reg.std2struc = np.linalg.inv(wsp.reg.struc2std)
  File "/opt/fmrib/fsltmp/fsl_3a805695/fslpython/envs/fslpython/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 522, in inv
    _assertRankAtLeast2(a)
  File "/opt/fmrib/fsltmp/fsl_3a805695/fslpython/envs/fslpython/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 201, in _assertRankAtLeast2
    'at least two-dimensional' % a.ndim)
numpy.linalg.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
```

**Comment by mcraig-ibme** [comment]
This was partly fixed by 7b76d0b503409069c7e56103523c046df1a9c45b which had not yet been released.

However another issue prevented nonlinear transformations from FSL_ANAT from being used - this has now been fixed by 0273b4abba003f680206796e65f57d2a7f154c17

Should now be fixed on master. Updated release required

**Comment by mcraig-ibme** [comment]
Fix confirmed, will be in next release.

**Comment by mcraig-ibme** [comment]
v0.1.0
