### ISSUE TITLE
Error reported using FSLANAT option on VE data

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/oxasl#5]
```
/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py:49: RuntimeWarning: invalid value encountered in double_scalars
  tag_rad = math.acos(LV_minus_RC[0] / np.linalg.norm(LV_minus_RC))
/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py:79: RuntimeWarning: invalid value encountered in greater
  th[two[enccyc, 2] > two[enccyc, 3]] = th[two[enccyc, 2] > two[enccyc, 3]] + 180
ERROR: /home/fs0/winokl/Programmes/oxasl/bin/veasl returned non-zero exit code: -6
Traceback (most recent call last):
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/oxford_asl.py", line 160, in main
    oxasl(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl/oxford_asl.py", line 187, in oxasl
    oxasl_ve.model_ve(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py", line 438, in model_ve
    num_vessels = _decode(wsp)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py", line 266, in _decode
    _decode_infer(wsp_init)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py", line 201, in _decode_infer
    flow, prob, extras, log = veaslc_wrapper(wsp, wsp.asldata, wsp.infer_mask)
  File "/home/fs0/winokl/Programmes/oxasl/oxasl_ve/veaslc_cli_wrapper.py", line 25, in veaslc_wrapper
    log=wsp.fsllog)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 980, in wrapper
    result = fot(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 646, in __call__
    result = func(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 1022, in wrapper
    return fot(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 646, in __call__
    result = func(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 1064, in wrapper
    return fot(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 646, in __call__
    result = func(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/wrappers/wrapperutils.py", line 188, in wrapper
    exitcode=exitcode)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/utils/run.py", line 370, in runfsl
    return run(*args, **kwargs)
  File "/home/fs0/winokl/Programmes/oxasl/fsl/utils/run.py", line 228, in run
    args[0], exitcode))
RuntimeError: /home/fs0/winokl/Programmes/oxasl/bin/veasl returned non-zero exit code: -6

```

**Comment by mcraig-ibme** [comment]
The following output was also reported but may not be related to the crash:

```
home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py:49: RuntimeWarning: invalid value encountered in double_scalars
  tag_rad = math.acos(LV_minus_RC[0] / np.linalg.norm(LV_minus_RC))

/home/fs0/winokl/Programmes/oxasl/oxasl_ve/api.py:79: RuntimeWarning: invalid value encountered in greater

  th[two[enccyc, 2] > two[enccyc, 3]] = th[two[enccyc, 2] > two[enccyc, 3]] + 180

ERROR: /home/fs0/winokl/Programmes/oxasl/bin/veasl returned non-zero exit code: -6
```

**Comment by mcraig-ibme** [comment]
This was caused by incorrect vessel location data. Will look to see if a better error message can be generated.
